### ISSUE TITLE
What about security matters?

### ISSUE THREAD

**Issue by panay** [parsnick/eloquentjs-client#2]
Hello! Question in the title.
Let me explain:
As I understand it, everyone will be able to make requests from the browser to the database?
How to use it in production?

**Comment by wietseva** [comment]
This client library doesn't access the database directly but through an Api  set up in Laravel  ([https://github.com/parsnick/eloquentjs](https://github.com/parsnick/eloquentjs)). The security is as thus managed by this api and Laravel, you can add rules to the Api to determine which actions you want to block/allow. 
You can see some examples at [http://parsnick.github.io/eloquentjs/server/](http://parsnick.github.io/eloquentjs/server/ )

**Comment by panay** [comment]
OK! Thank you for answer.

**Comment by panay** [comment]
Oh, stop. But that does not negate the fact that my entire base may be stolen

**Comment by parsnick** [comment]
I don't understand - perhaps you could post a code sample to illustrate the point?

This is a client-side library so it cannot access your database. From a security perspective, calling `Eloquent.Post.find(42)` is no different to coding an AJAX call manually like `jQuery.get('/api/posts/42')`. In both cases, it's entirely up to the server how it wants to respond.

The `parsnick/eloquentjs` PHP package integrates with Laravel to *assist* with building the server-side API, but at no point does it hook into the database and fetch or modify any data directly. By design, all requests *must* still go through your app. See the examples linked to by @wietseva

**Comment by panay** [comment]
Oh, I got it! Sorry for my stupidity. Thank you very much!
